development:
  adapter: postgresql
  encoding: unicode
  database: cd_dev_old
  pool: 5
  username:
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: cd_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cd_prod
  pool: 5
  username: college_desis
  password:

cucumber:
  <<: *test
