development:
  host: /var/pgsql_socket
  adapter: postgresql
  encoding: unicode
  database: cd_dev
  pool: 5
  username:
  password:

test:
  host: /var/pgsql_socket
  adapter: postgresql
  encoding: unicode
  database: cd_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cd_prod
  pool: 5
  username: college_desis
  password:
