#= require ./router
#= require ./adapter
#= require ./store
#= require_tree ./libs
#= require_tree ./models
#= require_tree ./routes
#= require_tree ./controllers
#= require_tree ./views
#= require_tree ./templates
#= require_self